---
version: '3.8'

services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: awsmicroservice
      POSTGRES_PASSWORD: awsmicroservice
      POSTGRES_DB: awsmicroservice
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U awsmicroservice"]
      interval: 5s
      timeout: 5s
      retries: 5
