[tool.black]
line-length = 100
target-version = ["py311"]
exclude = """
    venv
"""

[tool.isort]
profile = 'black'
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
line_length = 100
multi_line_output = 3
