apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpat-aws-microservice-deployment
  labels:
    app: dpat-aws-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dpat-aws-microservice # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: dpat-aws-microservice # this should match the selector in service.yml
    spec:
      serviceAccountName: dpat-aws-microservice-sa
      containers:
        - name: api
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: aws-microservice-secrets
                  key: aws_account_id
            - name: OIDC_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: aws-microservice-secrets
                  key: oidc_domain
            - name: OIDC_API_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: aws-microservice-secrets
                  key: oidc_api_audience
            - name: OIDC_ISSUER
              valueFrom:
                secretKeyRef:
                  name: aws-microservice-secrets
                  key: oidc_issuer
            - name: OIDC_ALGORITHMS
              valueFrom:
                secretKeyRef:
                  name: aws-microservice-secrets
                  key: oidc_algorithms
            - name: OIDC_EKS_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: aws-microservice-secrets
                  key: oidc_eks_provider
